name: Cypress E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Run tests in parallel across multiple containers
        containers: [1, 2, 3, 4]
    
    services:
      # MongoDB service for backend tests
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Start backend server
        run: |
          cd backend
          npm start &
          # Wait for backend to be ready
          npx wait-on http://localhost:3001/api/health --timeout 60000
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://localhost:27017/adopteunetudiant_test
          JWT_SECRET: test-secret-key

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Start frontend server
        run: |
          cd frontend
          npm start &
          # Wait for frontend to be ready
          npx wait-on http://localhost:3000 --timeout 60000
        env:
          CI: false

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: chrome
          headless: true
          record: true
          parallel: true
          group: 'E2E Tests'
          tag: ${{ github.event_name }}
          spec: |
            cypress/e2e/auth/*.cy.js,
            cypress/e2e/job-board/*.cy.js,
            cypress/e2e/dashboard/*.cy.js,
            cypress/e2e/navigation/*.cy.js,
            cypress/e2e/accessibility/*.cy.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_baseUrl: http://localhost:3000
          CYPRESS_apiUrl: http://localhost:3001/api

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.containers }}
          path: frontend/cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.containers }}
          path: frontend/cypress/videos
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results-${{ matrix.containers }}
          path: |
            frontend/cypress/results
            frontend/mochawesome-report
          retention-days: 30

  # Job to run accessibility tests separately
  accessibility-tests:
    runs-on: ubuntu-latest
    needs: cypress-run
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Start servers
        run: |
          cd backend && npm start &
          cd frontend && npm start &
          npx wait-on http://localhost:3000 http://localhost:3001/api/health --timeout 60000

      - name: Run accessibility tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: chrome
          headless: true
          spec: cypress/e2e/accessibility/*.cy.js
        env:
          CYPRESS_baseUrl: http://localhost:3000

  # Job to generate and publish test reports
  test-report:
    runs-on: ubuntu-latest
    needs: [cypress-run, accessibility-tests]
    if: always()
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          pattern: cypress-results-*
          merge-multiple: true
          path: test-results

      - name: Generate test report
        run: |
          # Merge test results and generate HTML report
          npx mochawesome-merge test-results/*.json > merged-report.json
          npx marge merged-report.json --reportDir public --inline

      - name: Deploy test report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: test-reports

  # Job to run performance tests
  performance-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[perf]')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Start servers
        run: |
          cd backend && npm start &
          cd frontend && npm start &
          npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Run performance tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: chrome
          headless: true
          spec: cypress/e2e/**/*.cy.js
          config: video=false,screenshotOnRunFailure=false
        env:
          CYPRESS_baseUrl: http://localhost:3000
          CYPRESS_performance: true

  # Job to run visual regression tests
  visual-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          npm install --save-dev cypress-image-diff-js

      - name: Start servers
        run: |
          cd backend && npm start &
          cd frontend && npm start &
          npx wait-on http://localhost:3000 --timeout 60000

      - name: Run visual regression tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: chrome
          headless: true
          spec: cypress/e2e/visual/*.cy.js
        env:
          CYPRESS_baseUrl: http://localhost:3000
          CYPRESS_updateSnapshots: false

      - name: Upload visual diff artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-diffs
          path: frontend/cypress/screenshots/visual-diffs
          retention-days: 7
